name: Mirror Plane Image

on:
  workflow_dispatch:
    inputs:

      image:
        description: "image name"
        required: true
        default: "plane-live"


jobs:

  mirror:

    runs-on: ubuntu-latest

    permissions:
      packages: write


    steps:

    - name: Login GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}


    - name: Mirror
      run: |

        case "${{ github.event.inputs.image }}" in

        plane-live)
          IMAGE=makeplane/plane-live:latest
          ;;

        plane-backend)
          IMAGE=makeplane/plane-backend:latest
          ;;

        plane-worker)
          IMAGE=makeplane/plane-worker:latest
          ;;

        plane-space)
          IMAGE=makeplane/plane-space:latest
          ;;

        *)
          echo "unknown image"
          exit 1
          ;;

        esac


        docker pull $IMAGE


        NAME=$(echo $IMAGE | sed 's/\//-/g' | sed 's/:/-/g')


        docker tag \
        $IMAGE \
        ghcr.io/${{ github.repository_owner }}/$NAME


        docker push \
        ghcr.io/${{ github.repository_owner }}/$NAME
