name: Mirror Plane Images


on:

  workflow_dispatch:



jobs:

  mirror:


    runs-on: ubuntu-latest


    permissions:

      contents: read

      packages: write



    steps:


    - name: Login GHCR

      uses: docker/login-action@v3

      with:

        registry: ghcr.io

        username: ${{ github.actor }}

        password: ${{ secrets.GITHUB_TOKEN }}



    - name: Mirror Plane Images

      run: |


        images=$(cat <<EOF

        plane-live makeplane/plane-live:latest

        plane-backend makeplane/plane-backend:latest

        plane-worker makeplane/plane-backend:latest

        plane-space makeplane/plane-space:latest

        plane-web makeplane/plane-web:latest

        plane-admin makeplane/plane-admin:latest

        EOF

        )



        while read NAME IMAGE

        do

          echo "Pulling $IMAGE"


          docker pull $IMAGE


          docker tag \

          $IMAGE \

          ghcr.io/${{ github.repository_owner }}/$NAME:latest



          docker push \

          ghcr.io/${{ github.repository_owner }}/$NAME:latest


        done <<< "$images"
